/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type NativeFMIndex = NativeFmIndex
export declare class NativeFmIndex {
  /**
   * Load a FASTA file and build an in-memory FM-Index.
   *
   * Blocking — call from the main thread during initialisation before
   * any concurrent access to this object.
   */
  constructor(fastaPath: string)
  /**
   * Stream alignment records into a Strand SharedArrayBuffer.
   *
   * `sab` must be `Buffer.from(sharedArrayBuffer)` — a Buffer that shares
   * memory with the SAB. The SAB must remain alive for the duration of this
   * call (i.e. keep a reference to it in the calling scope).
   *
   * Returns a Promise<void> that resolves when all queries have been
   * processed and STATUS_EOS has been written, or rejects on error.
   */
  streamAlignments(sab: Buffer, queries: Array<string>, maxMismatches?: number | undefined | null): Promise<unknown>
  /** Returns chromosome names in FASTA order (index = chrom_id). */
  chromNames(): Array<string>
}
